### ISSUE TITLE
[IDEA] Is it possible to target Firebase Cloud Function?

### ISSUE THREAD

**Issue by katopz** [cloudflare/miniflare#169]
## Motivation
Cloudflare worker/Rust is always my first choice but sometime it's too small or too limit to fit some lib/unsupported features.
So I've an idea to continue writing in `Rust` and deploy as `WASM` to Cloudflare (if its fit) or Firebase (if it's not).

## POC
- [x] Try run `wasm_bindgen` on Firebase Cloud Function to proof `wasm32-unknown-unknown` working fine.

## TODO
- [ ] Explore existing stacks (which is `miniflare`), find intersection then modify/fork from it if possible. 👈 I'm here.
- [ ] Or create my own template, use `firebase-tools` (nothing to do with `miniflare` in this case).
- [ ] Support `ENV` from `Firebase`.
- [ ] Support `Firestore` instead of `KV`.
- [ ] Support `JsValue`.
- [ ] Support `fetch`.
- [ ] Not sure.

That's a lot of `me-unknown-unknown` here, so the and answer can be.
- No, you're go in a wrong way don't do it, create some template from Firebase side, use firebase-tools then share crate would be easier.
- Yes, you can fork and modify some cargo, webpack, define cfg target this and that and then magic happen.

Any idea is welcome, Thanks!

**Comment by katopz** [comment]
Consider it done (partially) without `miniflare` https://github.com/katopz/hello-firebase-wasm
