### ISSUE TITLE
Tracking: Replacing polyfill dependencies with node.js native APIs

### ISSUE THREAD

**Issue by jasnell** [cloudflare/miniflare#56]
Just opening this as a way of tracking which polyfill dependencies can soon be replaced with official node.js apis...

* [ ] @mrbbot/node-fetch --> https://github.com/nodejs/undici
* [ ] @peculiar/webcrypto --> Node.js core WebCrypto impl
* [ ] event-target-shim --> Node.js core EventTarget impl
* [ ] formdata-node --> We should implement `FormData` in Node.js core
* [ ] web-streams-polyfill --> Node.js core Web Streams impl

**Comment by mrbbot** [comment]
Nice! 🎉 Thanks for collating these all together.

Lots of these have been implemented in [version 2](https://github.com/cloudflare/miniflare/tree/v2/packages). 🙂

I was planning on making Node 16 required for the next major version which should be released around the same time it becomes the Active LTS. Was considering making a `@miniflare/compat` package that hooked into the require of built-ins to replace them with these polyfill dependencies, but I'm not sure the extra maintainence work is worth it, especially as this is primarily a development tool.
